import { PlayerConfig, CameraConfig, ArenaConfig, WeaponConfig, WeaponType, EnemyType } from '../types';

export const PLAYER_CONFIG: PlayerConfig = {
  maxHealth: 100,
  maxArmor: 100,
  maxStamina: 100,
  height: 1.7,
  walkSpeed: 8,
  sprintSpeed: 12,
  jumpForce: 12,
  gravity: 35,
  groundAccel: 50,
  airAccel: 20,
  groundDecel: 30,
  airDecel: 5,
  jumpBuffer: 0.1,
  coyoteTime: 0.15,
  jumpCutMultiplier: 0.5,
  stepHeight: 0.5,
  staminaDrain: 20,
  staminaRegen: 15,
};

export const CAMERA_CONFIG: CameraConfig = {
  baseFOV: 75,
  sprintFOV: 85,
  jumpFOV: 78,
  landFOV: 70,
  fovLerpSpeed: 10,
  bobFrequency: 12,
  bobAmplitudeX: 0.015,
  bobAmplitudeY: 0.035,
  breathFrequency: 2,
  breathAmplitude: 0.005,
  jumpStretch: 0.2,
  mouseSensitivity: 0.002,
};

export const ARENA_CONFIG: ArenaConfig = {
  size: 60,
  wallHeight: 8,
};

const BASE_AUDIO_PATH = 'assets/audio/weapons/';

const DEFAULT_VISUALS = {
  muzzle: {
    lightColor: 0xffaa00,
    lightRange: 5,
    flashScale: { min: 0.5, max: 1.5 },
    flashDuration: 0.05,
    lightIntensity: 2,
    smokeParticles: 3,
    smokeSpeed: 0.5,
  },
  sprayPattern: {
    enabled: true,
    resetTime: 300,
    scale: 0.002,
    vertical: [1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 7, 6, 5],
    horizontal: [0, 0, 1, -1, 2, -2, 3, -3, 2, -2, 1, -1],
  },
  screen: {
    maxFovPunch: 5,
    fovPunch: 0.5,
    shakeIntensity: 0.1,
    maxChroma: 0.02,
    chromaIntensity: 0.005,
    shakeDecay: 0.9,
    fovPunchRecovery: 10,
    chromaDecay: 0.8,
  },
  animation: {
    swayAmount: 0.05,
    swayRecovery: 5,
    sprintLerpSpeed: 10,
    reloadLerpSpeed: 10,
    baseX: 0.25,
    baseY: -0.2,
    baseZ: -0.5,
    bobInfluence: 1,
    sprintOffsetX: -0.1,
    sprintOffsetY: -0.1,
    reloadDipY: -0.2,
    reloadRotX: -0.5,
    sprintRotZ: 0.5,
  },
};

export const WEAPON_CONFIG: WeaponConfig = {
  [WeaponType.AK47]: {
    name: 'AK-47',
    damage: 30,
    fireRate: 10,
    magSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.5,
    automatic: true,
    audio: {
      fire: BASE_AUDIO_PATH + 'AK47-Fire.mp3_aad0f6c9.mp3',
      reload: BASE_AUDIO_PATH + 'LMG-Reload.mp3',
    },
    recoil: {
      pitchAmount: 0.05,
      pitchRandom: 0.02,
      yawAmount: 0.02,
      yawRandom: 0.03,
      recoveryRate: 5,
      kickZ: 0.1,
      kickRotX: 0.1,
    },
    spread: {
      base: 0.0015,
      max: 0.008,
      increasePerShot: 0.0008,
      recoveryRate: 3,
    },
    ...DEFAULT_VISUALS
  },
  [WeaponType.AWP]: {
    name: 'AWP',
    damage: 100,
    fireRate: 0.8,
    magSize: 10,
    reserveAmmo: 30,
    reloadTime: 3.5,
    automatic: false,
    audio: {
      fire: BASE_AUDIO_PATH + 'AWP-Fire.mp3_1b838826.mp3',
      reload: BASE_AUDIO_PATH + 'Sniper-Reload.mp3_dbe31ae3.mp3',
    },
    recoil: {
      pitchAmount: 0.2,
      pitchRandom: 0.05,
      yawAmount: 0.05,
      yawRandom: 0.05,
      recoveryRate: 2,
      kickZ: 0.3,
      kickRotX: 0.3,
    },
    spread: {
      base: 0.0005,
      max: 0.006,
      increasePerShot: 0.005,
      recoveryRate: 1,
    },
    ...DEFAULT_VISUALS,
    muzzle: { ...DEFAULT_VISUALS.muzzle, lightRange: 8 },
    screen: { ...DEFAULT_VISUALS.screen, fovPunch: 2, shakeIntensity: 0.3 }
  },
  [WeaponType.LMG]: {
    name: 'LMG',
    damage: 25,
    fireRate: 12,
    magSize: 100,
    reserveAmmo: 200,
    reloadTime: 4.0,
    automatic: true,
    audio: {
      fire: BASE_AUDIO_PATH + 'LMG-Fire.mp3',
      reload: BASE_AUDIO_PATH + 'LMG-Reload.mp3',
    },
    recoil: {
      pitchAmount: 0.04,
      pitchRandom: 0.03,
      yawAmount: 0.03,
      yawRandom: 0.04,
      recoveryRate: 4,
      kickZ: 0.15,
      kickRotX: 0.15,
    },
    spread: {
      base: 0.0025,
      max: 0.012,
      increasePerShot: 0.0004,
      recoveryRate: 2,
    },
    ...DEFAULT_VISUALS,
    muzzle: { ...DEFAULT_VISUALS.muzzle, lightRange: 6 }
  },
  [WeaponType.M4]: {
    name: 'M4',
    damage: 28,
    fireRate: 11,
    magSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.2,
    automatic: true,
    audio: {
      fire: BASE_AUDIO_PATH + 'M4-Fire.mp3_1ebefbe9.mp3',
      reload: BASE_AUDIO_PATH + 'LMG-Reload.mp3',
    },
    recoil: {
      pitchAmount: 0.04,
      pitchRandom: 0.01,
      yawAmount: 0.01,
      yawRandom: 0.02,
      recoveryRate: 6,
      kickZ: 0.08,
      kickRotX: 0.08,
    },
    spread: {
      base: 0.0012,
      max: 0.007,
      increasePerShot: 0.0007,
      recoveryRate: 4,
    },
    ...DEFAULT_VISUALS
  },
  [WeaponType.Pistol]: {
    name: 'Pistol',
    damage: 20,
    fireRate: 6,
    magSize: 12,
    reserveAmmo: 48,
    reloadTime: 1.5,
    automatic: false,
    audio: {
      fire: BASE_AUDIO_PATH + 'Pistol-Fire.mp3_b6b25ed9.mp3',
      reload: BASE_AUDIO_PATH + 'Pistol-Reload.mp3_bb913d81.mp3',
    },
    recoil: {
      pitchAmount: 0.08,
      pitchRandom: 0.02,
      yawAmount: 0.01,
      yawRandom: 0.01,
      recoveryRate: 8,
      kickZ: 0.05,
      kickRotX: 0.05,
    },
    spread: {
      base: 0.001,
      max: 0.005,
      increasePerShot: 0.0015,
      recoveryRate: 5,
    },
    ...DEFAULT_VISUALS,
    muzzle: { ...DEFAULT_VISUALS.muzzle, lightRange: 3 }
  },
  [WeaponType.Scar]: {
    name: 'SCAR',
    damage: 35,
    fireRate: 9,
    magSize: 20,
    reserveAmmo: 60,
    reloadTime: 2.8,
    automatic: true,
    audio: {
      fire: BASE_AUDIO_PATH + 'Scar-Fire-1.mp3_d0e2f2c3.mp3',
      reload: BASE_AUDIO_PATH + 'Scar-Reload.mp3_ab2f464d.mp3',
      tail: BASE_AUDIO_PATH + 'Scar-Tail-Fire.mp3_05f3e5b0.mp3',
    },
    recoil: {
      pitchAmount: 0.06,
      pitchRandom: 0.02,
      yawAmount: 0.02,
      yawRandom: 0.02,
      recoveryRate: 4,
      kickZ: 0.12,
      kickRotX: 0.12,
    },
    spread: {
      base: 0.0018,
      max: 0.009,
      increasePerShot: 0.001,
      recoveryRate: 3,
    },
    ...DEFAULT_VISUALS
  },
  [WeaponType.Shotgun]: {
    name: 'Shotgun',
    damage: 15,
    fireRate: 1.5,
    magSize: 8,
    reserveAmmo: 32,
    reloadTime: 3.0,
    automatic: false,
    audio: {
      fire: BASE_AUDIO_PATH + 'Shotgun-Fire.mp3_c4d738ce.mp3',
      reload: BASE_AUDIO_PATH + 'Shotgun-Load.mp3_662a7e0b.mp3',
      cock: BASE_AUDIO_PATH + 'Shotgun-Cock.mp3_7ceb882c.mp3',
    },
    recoil: {
      pitchAmount: 0.3,
      pitchRandom: 0.1,
      yawAmount: 0.1,
      yawRandom: 0.1,
      recoveryRate: 2,
      kickZ: 0.4,
      kickRotX: 0.4,
    },
    spread: {
      base: 0.008,
      max: 0.015,
      increasePerShot: 0.007,
      recoveryRate: 2,
    },
    ...DEFAULT_VISUALS,
    muzzle: { ...DEFAULT_VISUALS.muzzle, lightRange: 7 },
    screen: { ...DEFAULT_VISUALS.screen, fovPunch: 1.5, shakeIntensity: 0.2 }
  },
  [WeaponType.Sniper]: {
    name: 'Sniper Rifle',
    damage: 90,
    fireRate: 1.0,
    magSize: 5,
    reserveAmmo: 20,
    reloadTime: 3.0,
    automatic: false,
    audio: {
      fire: BASE_AUDIO_PATH + 'Sniper-Fire.mp3_e5df2297.mp3',
      reload: BASE_AUDIO_PATH + 'Sniper-Reload.mp3_dbe31ae3.mp3',
      load: BASE_AUDIO_PATH + 'Sniper-Load.mp3_2ff42cc3.mp3',
      zoom: BASE_AUDIO_PATH + 'Sniper-Zoom.mp3_4e79b9b9.mp3',
    },
    recoil: {
      pitchAmount: 0.25,
      pitchRandom: 0.05,
      yawAmount: 0.05,
      yawRandom: 0.05,
      recoveryRate: 2,
      kickZ: 0.35,
      kickRotX: 0.35,
    },
    spread: {
      base: 0.0003,
      max: 0.005,
      increasePerShot: 0.004,
      recoveryRate: 1,
    },
    ...DEFAULT_VISUALS,
    muzzle: { ...DEFAULT_VISUALS.muzzle, lightRange: 8 },
    screen: { ...DEFAULT_VISUALS.screen, fovPunch: 2, shakeIntensity: 0.3 }
  },
  [WeaponType.Tec9]: {
    name: 'Tec-9',
    damage: 22,
    fireRate: 14,
    magSize: 24,
    reserveAmmo: 72,
    reloadTime: 2.0,
    automatic: true,
    audio: {
      fire: BASE_AUDIO_PATH + 'Tec-9-Fire.mp3_1ef19caa.mp3',
      reload: BASE_AUDIO_PATH + 'Tec-9-Reload.mp3_c6b5e89d.mp3',
      load: BASE_AUDIO_PATH + 'Tec-9-Load.mp3_abbbfbd5.mp3',
      tail: BASE_AUDIO_PATH + 'Tec-9-Tail-Fire.mp3_d014dc4e.mp3',
    },
    recoil: {
      pitchAmount: 0.06,
      pitchRandom: 0.03,
      yawAmount: 0.04,
      yawRandom: 0.04,
      recoveryRate: 6,
      kickZ: 0.07,
      kickRotX: 0.07,
    },
    spread: {
      base: 0.003,
      max: 0.011,
      increasePerShot: 0.0006,
      recoveryRate: 4,
    },
    ...DEFAULT_VISUALS,
    muzzle: { ...DEFAULT_VISUALS.muzzle, lightRange: 4 }
  },
};

export const ENEMY_TYPES: Record<string, EnemyType> = {
  grunt: {
    health: 50,
    speed: 4,
    damage: 10,
    fireRate: 1,
    accuracy: 0.15,
    color: 0x22c55e,
    score: 100,
  },
  soldier: {
    health: 80,
    speed: 5,
    damage: 15,
    fireRate: 2,
    accuracy: 0.1,
    color: 0xf59e0b,
    score: 200,
  },
  heavy: {
    health: 150,
    speed: 2.5,
    damage: 25,
    fireRate: 0.5,
    accuracy: 0.2,
    color: 0xef4444,
    score: 300,
  },
};
